name: Metrics
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: calltekk
          token: ${{ secrets.GITHUB_TOKEN }}
          template: classic
          base: header, activity, repositories
          filename: github-metrics.svg
